hwsc-org/hwsc-user-svc

.gitignore
Gopkg.lock
Gopkg.toml
README.md
conf/config.go
main.go
service/db.go
service/db_test.go
service/error.go
service/service.go

**Overall coverage:**
**Unit test coverage per package file:**
**Parts not covered by unit test:**

Implement and write test for persistent mongo

---

.gitignore
Gopkg.lock
Gopkg.toml
service/db.go
service/db_test.go
service/service.go
service/service_test.go

- changed naming for db constants
- added extra parameter for db functions to track type of mongo client
*overall coverage*
*individual coverage*
*parts not tested*

Implement and unit test GetStatus

---

service/db.go
service/db_test.go
service/email.go
service/email_test.go
service/error.go
service/service.go
service/service_test.go
service/utility.go
service/utility_test.go

- golinted and formatted
- unit tested deleteUser
- created more utility functions and unit tested
- validate uuid
- test existing uuid

Implement DeleteUser service

---

service/db.go
service/email.go
service/email_test.go
service/service.go
service/service_test.go

- golinted and formatted
- added getUserRow db utility function
- unit tested GetUser

Implement GetUser service

---

service/email.go
service/email_test.go
service/error.go
service/service.go
service/service_test.go
service/utility.go
service/utility_test.go

- Moved generateEmailToken function to email.go
- Unit tested generateEmailToken
- Unit tested race conditions for uuid/token generator
- golinted and formatted

Synchronize CreateUser

---

Gopkg.lock
Gopkg.toml
service/db.go
service/db_test.go
service/error.go
service/service.go
service/service_test.go

- Implemented UpdateUser
- Included sync
- Unit tested UpdateUser and db utility UpdateUserRow
- Golinted and formatted

Implement UpdateUser

---

Dockerfile
conf/config.go

Update environment variable in config.go

---

Gopkg.lock
consts/errors.go
consts/tags.go
service/db.go
service/service.go
service/service_test.go
service/utility.go
service/utility_test.go

Task: https://github.com/hwsc-org/hwsc-user-svc/issues/8
- implemented validatePassword and comparePassword in utility.go
- wrote unit test for autheticateUser, and new additions to utility.go
- unit tested

Implement Authenticate User

---

Gopkg.lock
service/db.go
service/service.go

Task: https://github.com/hwsc-org/hwsc-user-svc/issues/37
In addition:
- deleted uuid from uuidMapLocker for nonvalid uuid in checkUserExists
- ran unit test
- ran integration test

Modify CreateUser to include permission_level

---

Gopkg.lock
consts/errors.go
consts/tags.go
service/db.go
service/db_test.go
service/service.go
service/service_test.go
service/utility.go
service/utility_test.go

Task: https://github.com/hwsc-org/hwsc-user-svc/issues/42
- created db utility for inserting secret
- created utility for generating expiration date
- unit tested

Implement NewSecret service

---

consts/errors.go
service/db.go
service/db_test.go
service/service.go
service/service_test.go
service/utility_test.go

- implemented db utility for getActiveSecret and deactivateSecret
- updated NewSecret to deactivate current activated secret (if any)
- unit test getActiveSecret and deactivateSecret
- updated unit testing for NewSecret
- ran all unit tests

Update NewSecret service

---

Gopkg.lock
consts/tags.go
service/db.go
service/db_test.go
service/service.go
service/service_test.go

Task: https://github.com/hwsc-org/hwsc-user-svc/issues/41
- unit tested GetSecret
- changed implementation for db utility getActiveSecretRow:
- made it return nil if not found
- made it return a pb.Secret object if found
- ran all unit tests

Implement GetSecret service

---

Gopkg.lock
consts/errors.go
consts/tags.go
service/db.go
service/db_test.go
service/service.go
service/service_test.go

Task: https://github.com/hwsc-org/hwsc-user-svc/issues/39, https://github.com/hwsc-org/hwsc-user-svc/issues/54
- generated expiration timestamp for jwt body
- implement db utility to insert new token into db
- updated GetSecret service to insert new secret if no active keys present
- updated GetSecret unit test to test if new secret is generated
- unit tested GetToken and insertJWToken
- unit tested all

Implement GetToken service

---

consts/errors.go
service/consts_test.go
service/db.go
service/db_test.go
service/service.go
service/service_test.go

task: https://github.com/hwsc-org/hwsc-user-svc/issues/58
- updated GetToken to retrieve existing token if user is already present in token table
- implemented and unit tested getExistingToken
- moved unit test utility functions to own file called consts_test.go
- ran all unit tests

Implement retrieving existing token

---

.gitignore
consts/errors.go
consts/tags.go
service/consts_test.go
service/db.go
service/db_test.go
service/service.go
service/service_test.go

task: https://github.com/hwsc-org/hwsc-user-svc/issues/40
- added periods to comments (for godoc readability)
- implemented db utility for looking up tokens against given token
- unit tested new utility and service
- checked that authority object is set to zero values
- unit tested all

Implement VerifyToken service

---

conf/config.go
consts/tags.go
service/db.go
service/service.go
service/service_test.go

- uses updated local environment variables

Improve db connection string format

---

go.mod
go.sum
service/db.go
service/service.go

unit tested, linted and formatted

Remove hard coded values when passing values to db

---

azure-pipelines-pr-template.yml
azure-pipelines.yml
service/email.go
service/email_test.go
service/service_test.go

Update master azure pipeline yaml file

---

azure-pipelines-pr-test.yml
azure-pipelines.yml

This change contains the following:
- Fix PR pipeline to not tag a build id
- Fail the pipeline if a test fails
Feel free to merge this

Fail test as required

---

azure-pipelines-pr-test.yml
go.mod
go.sum
service/consts_test.go
service/db.go
service/db_test.go
service/service.go
service/test_fixtures/psql/0_initial_schemas.up.sql

closes #76
- renamed user_svc.pending_tokens to user_svc.email_tokens
- rename user_security.tokens to user_security.auth_tokens
- renamed jwtExpirationTime to authTokenExpirationTime

[WIP] Renaming tables, columns, and variables
